[application]
name = "dioxus_site"

[web.app]
title = "dioxus_site"
base_path = ""

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []

[web.watcher]
watch_path = ["src", "assets"]
